version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: my-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  # kafka:
  #   image: confluentinc/cp-kafka:6.1.1
  #   container_name: my-kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:6.1.1
  #   container_name: my-zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181


  nodejs:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "9080:9080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - redis
      - elasticsearch
      # - kafka
      # - zookeeper